set search_path= chatbot, public, pgml;
select chatbot.restart_session(:ten, :ses);
select init_session(:ten, :ses);
select chatbot.process_dialogue(:ten, :ses, :us, 'Quais são os requisitos de segurança, qualidade e eficácia que o Serviço Tipo III deve adotar ao utilizar materiais de uso laboratorial geral?');
select chatbot.process_dialogue(:ten, :ses, :us, 'Como o Serviço Tipo III deve garantir a rastreabilidade de todos os insumos, reagentes e demais componentes utilizados na análise?');
select chatbot.process_dialogue(:ten, :ses, :us, 'Quais são as medidas que o Serviço Tipo III deve adotar para prevenir a recorrência de eventos adversos e queixas técnicas associados aos instrumentos e acessórios regularizados junto à Anvisa?');
select chatbot.process_dialogue(:ten, :ses, :us, 'Como o Serviço Tipo III deve manter registros das medidas e verificações dos instrumentos e acessórios regularizados junto à Anvisa?');
select chatbot.process_dialogue(:ten, :ses, :us, 'Quais são as obrigações do Serviço Tipo III em relação à fornecimento de informações necessárias sobre os materiais de uso laboratorial geral e desinfecção regularizados junto à Anvisa?');
select chatbot.process_dialogue(:ten, :ses, :us, 'Como o Serviço Tipo III deve definir limites de risco, valores críticos ou de alerta, para os exames que utilizam materiais de uso laboratorial geral e desinfecção regularizados junto à Anvisa?');
select chatbot.process_dialogue(:ten, :ses, :us, 'Quais são as consequências para o Serviço Tipo III em caso de não cumprimento dos requisitos dispostos nesta Resolução em relação à utilização de materiais de uso laboratorial geral e desinfecção regularizados junto à Anvisa?');
select chatbot.process_dialogue(:ten, :ses, :us, 'quais as condicoes para quem nao cumprir os requisitos?');
select chatbot.process_dialogue(:ten, :ses, :us, 'enumere utilizando topicos quais as condicoes para quem nao cumprir os requisitos?');